name: DeployToServer
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "markdown"
      - uses: actions/checkout@v4
        with:
          repository: 'temme-stefan/markdown-bundler'
          path: "bundler"
      - uses: actions/setup-node@v4
        with:
          node-version: 20.4
      - name: link markdown
        run: ln -s "$GITHUB_WORKSPACE/markdown" "$GITHUB_WORKSPACE/bundler/markdownfiles/markdown"
      - name: Install Dependecies
        run: cd "$GITHUB_WORKSPACE/bundler"; npm install
      - name: Build
        run: cd "$GITHUB_WORKSPACE/bundler"; npm run build
      - name: deploy
        run: cd "$GITHUB_WORKSPACE/bundler"; npm run deploy
